<?php

return [
    'vendor_settings' => [
        'pixel' => '',
        'crm' => '',
        'domain' => ''
    ],

    'settings' => [
        'street' => '1 Quiet Street',
        'locality' => 'Alagbado',
        'city' => 'Ikeja',
        'state' => 'Lagos',
        'code' => '',
        'country' => 'Nigeria',
        'phone' => '08012345678',
        'email' => 'info@marketstro.com',
        'twitter' => '',
        'facebook' => '',
        'instagram' => '',
        'tiktok' => '',
        'linkedin' => '',
        'whatsapp' => '',
        'youtube' => '',
    ],


    'permissions' => [
        ['name' => 'adverts'],
        ['name' => 'announcements'],
    ],

    'cms' => [
        ['slug' => 'how-to-buy', 'title' => 'How to buy'],
    ],

    'departments' => [
        'Executive Leadership' => [
            ['title' => 'CEO (Chief Executive Officer)'],
            ['title' => 'CFO (Chief Financial Officer)'],
            ['title' => 'COO (Chief Operating Officer)'],
            ['title' => 'CTO (Chief Technology Officer)'],
            ['title' => 'CMO (Chief Marketing Officer)'],
            ['title' => 'CHRO (Chief Human Resources Officer)'],
        ],
        'Operations' => [
            ['title' => 'Operations Manager'],
            ['title' => 'Production or Manufacturing'],
            ['title' => 'Supply Chain and Logistics'],
            ['title' => 'Quality Assurance'],
        ],
        'Finance and Accounting' => [
            ['title' => 'Finance Manager'],
            ['title' => 'Accounting'],
            ['title' => 'Treasury'],
            ['title' => 'Financial Planning and Analysis'],
        ],
        'Human Resources' => [
            ['title' => 'HR Manager'],
            ['title' => 'Recruitment and Talent Acquisition'],
            ['title' => 'Employee Relations'],
            ['title' => 'Training and Development'],
        ],
        'Sales and Marketing' => [
            ['title' => 'Sales Manager'],
            ['title' => 'Marketing Manager'],
            ['title' => 'Customer Service'],
            ['title' => 'Public Relations'],
        ],
        'Information Technology (IT)' => [
            ['title' => 'IT Manager'],
            ['title' => 'Systems and Network Administration'],
            ['title' => 'Software Development'],
            ['title' => 'IT Support'],
        ],
        'Research and Development (R&D)' => [
            ['title' => 'R&D Manager'],
            ['title' => 'Product Development'],
            ['title' => 'Innovation'],
        ],
        'Customer Support' => [
            ['title' => 'Customer Support Manager'],
            ['title' => 'Help Desk'],
            ['title' => 'Technical Support'],
        ],
        'Legal and Compliance' => [
            ['title' => 'Legal Counsel'],
            ['title' => 'Compliance Officer'],
        ],
        'Administrative Services' => [
            ['title' => 'Administrative Manager'],
            ['title' => 'Facilities Management'],
            ['title' => 'Office Services'],
        ],
        'Marketing Communications' => [
            ['title' => 'Marketing Communications Manager'],
            ['title' => 'Advertising'],
            ['title' => 'Public Relations'],
        ]
    ],

    'colors' => [
        ['name' => 'AliceBlue', 'code' => '#F0F8FF'],
        ['name' => 'AntiqueWhite', 'code' => '#FAEBD7'],
        ['name' => 'Aqua', 'code' => '#00FFFF'],
        ['name' => 'Aquamarine', 'code' => '#7FFFD4'],
        ['name' => 'Azure', 'code' => '#F0FFFF'],
        ['name' => 'Beige', 'code' => '#F5F5DC'],
        ['name' => 'Bisque', 'code' => '#FFE4C4'],
        ['name' => 'Black', 'code' => '#000000'],
        ['name' => 'BlanchedAlmond', 'code' => '#FFEBCD'],
        ['name' => 'Blue', 'code' => '#0000FF'],
        ['name' => 'BlueViolet', 'code' => '#8A2BE2'],
        ['name' => 'Brown', 'code' => '#A52A2A'],
        ['name' => 'BurlyWood', 'code' => '#DEB887'],
        ['name' => 'CadetBlue', 'code' => '#5F9EA0'],
        ['name' => 'Chartreuse', 'code' => '#7FFF00'],
        ['name' => 'Chocolate', 'code' => '#D2691E'],
        ['name' => 'Coral', 'code' => '#FF7F50'],
        ['name' => 'CornflowerBlue', 'code' => '#6495ED'],
        ['name' => 'Cornsilk', 'code' => '#FFF8DC'],
        ['name' => 'Crimson', 'code' => '#DC143C'],
        ['name' => 'Cyan', 'code' => '#00FFFF'],
        ['name' => 'DarkBlue', 'code' => '#00008B'],
        ['name' => 'DarkCyan', 'code' => '#008B8B'],
        ['name' => 'DarkGoldenRod', 'code' => '#B8860B'],
        ['name' => 'DarkGray', 'code' => '#A9A9A9'],
        ['name' => 'DarkGrey', 'code' => '#A9A9A9'],
        ['name' => 'DarkGreen', 'code' => '#006400'],
        ['name' => 'DarkKhaki', 'code' => '#BDB76B'],
        ['name' => 'DarkMagenta', 'code' => '#8B008B'],
        ['name' => 'DarkOliveGreen', 'code' => '#556B2F'],
        ['name' => 'DarkOrange', 'code' => '#FF8C00'],
        ['name' => 'DarkOrchid', 'code' => '#9932CC'],
        ['name' => 'DarkRed', 'code' => '#8B0000'],
        ['name' => 'DarkSalmon', 'code' => '#E9967A'],
        ['name' => 'DarkSeaGreen', 'code' => '#8FBC8F'],
        ['name' => 'DarkSlateBlue', 'code' => '#483D8B'],
        ['name' => 'DarkSlateGray', 'code' => '#2F4F4F'],
        ['name' => 'DarkSlateGrey', 'code' => '#2F4F4F'],
        ['name' => 'DarkTurquoise', 'code' => '#00CED1'],
        ['name' => 'DarkViolet', 'code' => '#9400D3'],
        ['name' => 'DeepPink', 'code' => '#FF1493'],
        ['name' => 'DeepSkyBlue', 'code' => '#00BFFF'],
        ['name' => 'DimGray', 'code' => '#696969'],
        ['name' => 'DimGrey', 'code' => '#696969'],
        ['name' => 'DodgerBlue', 'code' => '#1E90FF'],
        ['name' => 'FireBrick', 'code' => '#B22222'],
        ['name' => 'FloralWhite', 'code' => '#FFFAF0'],
        ['name' => 'ForestGreen', 'code' => '#228B22'],
        ['name' => 'Fuchsia', 'code' => '#FF00FF'],
        ['name' => 'Gainsboro', 'code' => '#DCDCDC'],
        ['name' => 'GhostWhite', 'code' => '#F8F8FF'],
        ['name' => 'Gold', 'code' => '#FFD700'],
        ['name' => 'GoldenRod', 'code' => '#DAA520'],
        ['name' => 'Gray', 'code' => '#808080'],
        ['name' => 'Grey', 'code' => '#808080'],
        ['name' => 'Green', 'code' => '#008000'],
        ['name' => 'GreenYellow', 'code' => '#ADFF2F'],
        ['name' => 'HoneyDew', 'code' => '#F0FFF0'],
        ['name' => 'HotPink', 'code' => '#FF69B4'],
        ['name' => 'IndianRed', 'code' => '#CD5C5C'],
        ['name' => 'Indigo', 'code' => '#4B0082'],
        ['name' => 'Ivory', 'code' => '#FFFFF0'],
        ['name' => 'Khaki', 'code' => '#F0E68C'],
        ['name' => 'Lavender', 'code' => '#E6E6FA'],
        ['name' => 'LavenderBlush', 'code' => '#FFF0F5'],
        ['name' => 'LawnGreen', 'code' => '#7CFC00'],
        ['name' => 'LemonChiffon', 'code' => '#FFFACD'],
        ['name' => 'LightBlue', 'code' => '#ADD8E6'],
        ['name' => 'LightCoral', 'code' => '#F08080'],
        ['name' => 'LightCyan', 'code' => '#E0FFFF'],
        ['name' => 'LightGoldenRodYellow', 'code' => '#FAFAD2'],
        ['name' => 'LightGray', 'code' => '#D3D3D3'],
        ['name' => 'LightGrey', 'code' => '#D3D3D3'],
        ['name' => 'LightGreen', 'code' => '#90EE90'],
        ['name' => 'LightPink', 'code' => '#FFB6C1'],
        ['name' => 'LightSalmon', 'code' => '#FFA07A'],
        ['name' => 'LightSeaGreen', 'code' => '#20B2AA'],
        ['name' => 'LightSkyBlue', 'code' => '#87CEFA'],
        ['name' => 'LightSlateGray', 'code' => '#778899'],
        ['name' => 'LightSlateGrey', 'code' => '#778899'],
        ['name' => 'LightSteelBlue', 'code' => '#B0C4DE'],
        ['name' => 'LightYellow', 'code' => '#FFFFE0'],
        ['name' => 'Lime', 'code' => '#00FF00'],
        ['name' => 'LimeGreen', 'code' => '#32CD32'],
        ['name' => 'Linen', 'code' => '#FAF0E6'],
        ['name' => 'Magenta', 'code' => '#FF00FF'],
        ['name' => 'Maroon', 'code' => '#800000'],
        ['name' => 'MediumAquaMarine', 'code' => '#66CDAA'],
        ['name' => 'MediumBlue', 'code' => '#0000CD'],
        ['name' => 'MediumOrchid', 'code' => '#BA55D3'],
        ['name' => 'MediumPurple', 'code' => '#9370DB'],
        ['name' => 'MediumSeaGreen', 'code' => '#3CB371'],
        ['name' => 'MediumSlateBlue', 'code' => '#7B68EE'],
        ['name' => 'MediumSpringGreen', 'code' => '#00FA9A'],
        ['name' => 'MediumTurquoise', 'code' => '#48D1CC'],
        ['name' => 'MediumVioletRed', 'code' => '#C71585'],
        ['name' => 'MidnightBlue', 'code' => '#191970'],
        ['name' => 'MintCream', 'code' => '#F5FFFA'],
        ['name' => 'MistyRose', 'code' => '#FFE4E1'],
        ['name' => 'Moccasin', 'code' => '#FFE4B5'],
        ['name' => 'NavajoWhite', 'code' => '#FFDEAD'],
        ['name' => 'Navy', 'code' => '#000080'],
        ['name' => 'OldLace', 'code' => '#FDF5E6'],
        ['name' => 'Olive', 'code' => '#808000'],
        ['name' => 'OliveDrab', 'code' => '#6B8E23'],
        ['name' => 'Orange', 'code' => '#FFA500'],
        ['name' => 'OrangeRed', 'code' => '#FF4500'],
        ['name' => 'Orchid', 'code' => '#DA70D6'],
        ['name' => 'PaleGoldenRod', 'code' => '#EEE8AA'],
        ['name' => 'PaleGreen', 'code' => '#98FB98'],
        ['name' => 'PaleTurquoise', 'code' => '#AFEEEE'],
        ['name' => 'PaleVioletRed', 'code' => '#DB7093'],
        ['name' => 'PapayaWhip', 'code' => '#FFEFD5'],
        ['name' => 'PeachPuff', 'code' => '#FFDAB9'],
        ['name' => 'Peru', 'code' => '#CD853F'],
        ['name' => 'Pink', 'code' => '#FFC0CB'],
        ['name' => 'Plum', 'code' => '#DDA0DD'],
        ['name' => 'PowderBlue', 'code' => '#B0E0E6'],
        ['name' => 'Purple', 'code' => '#800080'],
        ['name' => 'RebeccaPurple', 'code' => '#663399'],
        ['name' => 'Red', 'code' => '#FF0000'],
        ['name' => 'RosyBrown', 'code' => '#BC8F8F'],
        ['name' => 'RoyalBlue', 'code' => '#4169E1'],
        ['name' => 'SaddleBrown', 'code' => '#8B4513'],
        ['name' => 'Salmon', 'code' => '#FA8072'],
        ['name' => 'SandyBrown', 'code' => '#F4A460'],
        ['name' => 'SeaGreen', 'code' => '#2E8B57'],
        ['name' => 'SeaShell', 'code' => '#FFF5EE'],
        ['name' => 'Sienna', 'code' => '#A0522D'],
        ['name' => 'Silver', 'code' => '#C0C0C0'],
        ['name' => 'SkyBlue', 'code' => '#87CEEB'],
        ['name' => 'SlateBlue', 'code' => '#6A5ACD'],
        ['name' => 'SlateGray', 'code' => '#708090'],
        ['name' => 'SlateGrey', 'code' => '#708090'],
        ['name' => 'Snow', 'code' => '#FFFAFA'],
        ['name' => 'SpringGreen', 'code' => '#00FF7F'],
        ['name' => 'SteelBlue', 'code' => '#4682B4'],
        ['name' => 'Tan', 'code' => '#D2B48C'],
        ['name' => 'Teal', 'code' => '#008080'],
        ['name' => 'Thistle', 'code' => '#D8BFD8'],
        ['name' => 'Tomato', 'code' => '#FF6347'],
        ['name' => 'Turquoise', 'code' => '#40E0D0'],
        ['name' => 'Violet', 'code' => '#EE82EE'],
        ['name' => 'Wheat', 'code' => '#F5DEB3'],
        ['name' => 'White', 'code' => '#FFFFFF'],
        ['name' => 'WhiteSmoke', 'code' => '#F5F5F5'],
        ['name' => 'Yellow', 'code' => '#FFFF00'],
        ['name' => 'YellowGreen', 'code' => '#9ACD32']
    ],

    'currencies' => [
        ['name' => 'Naira', 'symbol' => 'N', 'code' => 'NGN', 'sell_rate' => 1, 'buy_rate' => 1, 'base_currency' => 1],
        ['name' => 'US Dollar', 'symbol' => '$', 'code' => 'USD', 'sell_rate' => 650, 'buy_rate' => 550, 'base_currency' => 0],
    ],

    'countries' => [
        ["code" => "AF", "name" => "Afghanistan", "phone" => "93", "symbol" => "؋", "currency" => "AFN"],
        ["code" => "AX", "name" => "Aland Islands", "phone" => "358", "symbol" => "€", "currency" => "EUR"],
        ["code" => "AL", "name" => "Albania", "phone" => "355", "symbol" => "Lek", "currency" => "ALL"],
        ["code" => "DZ", "name" => "Algeria", "phone" => "213", "symbol" => "دج", "currency" => "DZD"],
        ["code" => "AS", "name" => "American Samoa", "phone" => "1684", "symbol" => "$", "currency" => "USD"],
        ["code" => "AD", "name" => "Andorra", "phone" => "376", "symbol" => "€", "currency" => "EUR"],
        ["code" => "AO", "name" => "Angola", "phone" => "244", "symbol" => "Kz", "currency" => "AOA"],
        ["code" => "AI", "name" => "Anguilla", "phone" => "1264", "symbol" => "$", "currency" => "XCD"],
        ["code" => "AQ", "name" => "Antarctica", "phone" => "672", "symbol" => "$", "currency" => "AAD"],
        ["code" => "AG", "name" => "Antigua and Barbuda", "phone" => "1268", "symbol" => "$", "currency" => "XCD"],
        ["code" => "AR", "name" => "Argentina", "phone" => "54", "symbol" => "$", "currency" => "ARS"],
        ["code" => "AM", "name" => "Armenia", "phone" => "374", "symbol" => "֏", "currency" => "AMD"],
        ["code" => "AW", "name" => "Aruba", "phone" => "297", "symbol" => "ƒ", "currency" => "AWG"],
        ["code" => "AU", "name" => "Australia", "phone" => "61", "symbol" => "$", "currency" => "AUD"],
        ["code" => "AT", "name" => "Austria", "phone" => "43", "symbol" => "€", "currency" => "EUR"],
        ["code" => "AZ", "name" => "Azerbaijan", "phone" => "994", "symbol" => "m", "currency" => "AZN"],
        ["code" => "BS", "name" => "Bahamas", "phone" => "1242", "symbol" => "B$", "currency" => "BSD"],
        ["code" => "BH", "name" => "Bahrain", "phone" => "973", "symbol" => ".د.ب", "currency" => "BHD"],
        ["code" => "BD", "name" => "Bangladesh", "phone" => "880", "symbol" => "৳", "currency" => "BDT"],
        ["code" => "BB", "name" => "Barbados", "phone" => "1246", "symbol" => "Bds$", "currency" => "BBD"],
        ["code" => "BY", "name" => "Belarus", "phone" => "375", "symbol" => "Br", "currency" => "BYN"],
        ["code" => "BE", "name" => "Belgium", "phone" => "32", "symbol" => "€", "currency" => "EUR"],
        ["code" => "BZ", "name" => "Belize", "phone" => "501", "symbol" => "$", "currency" => "BZD"],
        ["code" => "BJ", "name" => "Benin", "phone" => "229", "symbol" => "CFA", "currency" => "XOF"],
        ["code" => "BM", "name" => "Bermuda", "phone" => "1441", "symbol" => "$", "currency" => "BMD"],
        ["code" => "BT", "name" => "Bhutan", "phone" => "975", "symbol" => "Nu.", "currency" => "BTN"],
        ["code" => "BO", "name" => "Bolivia", "phone" => "591", "symbol" => "Bs.", "currency" => "BOB"],
        ["code" => "BQ", "name" => "Bonaire, Sint Eustatius and Saba", "phone" => "599", "symbol" => "$", "currency" => "USD"],
        ["code" => "BA", "name" => "Bosnia and Herzegovina", "phone" => "387", "symbol" => "KM", "currency" => "BAM"],
        ["code" => "BW", "name" => "Botswana", "phone" => "267", "symbol" => "P", "currency" => "BWP"],
        ["code" => "BV", "name" => "Bouvet Island", "phone" => "55", "symbol" => "kr", "currency" => "NOK"],
        ["code" => "BR", "name" => "Brazil", "phone" => "55", "symbol" => "R$", "currency" => "BRL"],
        ["code" => "IO", "name" => "British Indian Ocean Territory", "phone" => "246", "symbol" => "$", "currency" => "USD"],
        ["code" => "BN", "name" => "Brunei Darussalam", "phone" => "673", "symbol" => "B$", "currency" => "BND"],
        ["code" => "BG", "name" => "Bulgaria", "phone" => "359", "symbol" => "Лв.", "currency" => "BGN"],
        ["code" => "BF", "name" => "Burkina Faso", "phone" => "226", "symbol" => "CFA", "currency" => "XOF"],
        ["code" => "BI", "name" => "Burundi", "phone" => "257", "symbol" => "FBu", "currency" => "BIF"],
        ["code" => "KH", "name" => "Cambodia", "phone" => "855", "symbol" => "KHR", "currency" => "KHR"],
        ["code" => "CM", "name" => "Cameroon", "phone" => "237", "symbol" => "FCFA", "currency" => "XAF"],
        ["code" => "CA", "name" => "Canada", "phone" => "1", "symbol" => "$", "currency" => "CAD"],
        ["code" => "CV", "name" => "Cape Verde", "phone" => "238", "symbol" => "$", "currency" => "CVE"],
        ["code" => "KY", "name" => "Cayman Islands", "phone" => "1345", "symbol" => "$", "currency" => "KYD"],
        ["code" => "CF", "name" => "Central African Republic", "phone" => "236", "symbol" => "FCFA", "currency" => "XAF"],
        ["code" => "TD", "name" => "Chad", "phone" => "235", "symbol" => "FCFA", "currency" => "XAF"],
        ["code" => "CL", "name" => "Chile", "phone" => "56", "symbol" => "$", "currency" => "CLP"],
        ["code" => "CN", "name" => "China", "phone" => "86", "symbol" => "¥", "currency" => "CNY"],
        ["code" => "CX", "name" => "Christmas Island", "phone" => "61", "symbol" => "$", "currency" => "AUD"],
        ["code" => "CC", "name" => "Cocos (Keeling) Islands", "phone" => "672", "symbol" => "$", "currency" => "AUD"],
        ["code" => "CO", "name" => "Colombia", "phone" => "57", "symbol" => "$", "currency" => "COP"],
        ["code" => "KM", "name" => "Comoros", "phone" => "269", "symbol" => "CF", "currency" => "KMF"],
        ["code" => "CG", "name" => "Congo", "phone" => "242", "symbol" => "FC", "currency" => "XAF"],
        ["code" => "CD", "name" => "Congo, Democratic Republic of the Congo", "phone" => "242", "symbol" => "FC", "currency" => "CDF"],
        ["code" => "CK", "name" => "Cook Islands", "phone" => "682", "symbol" => "$", "currency" => "NZD"],
        ["code" => "CR", "name" => "Costa Rica", "phone" => "506", "symbol" => "₡", "currency" => "CRC"],
        ["code" => "CI", "name" => "Cote D'Ivoire", "phone" => "225", "symbol" => "CFA", "currency" => "XOF"],
        ["code" => "HR", "name" => "Croatia", "phone" => "385", "symbol" => "kn", "currency" => "HRK"],
        ["code" => "CU", "name" => "Cuba", "phone" => "53", "symbol" => "$", "currency" => "CUP"],
        ["code" => "CW", "name" => "Curacao", "phone" => "599", "symbol" => "ƒ", "currency" => "ANG"],
        ["code" => "CY", "name" => "Cyprus", "phone" => "357", "symbol" => "€", "currency" => "EUR"],
        ["code" => "CZ", "name" => "Czech Republic", "phone" => "420", "symbol" => "Kč", "currency" => "CZK"],
        ["code" => "DK", "name" => "Denmark", "phone" => "45", "symbol" => "Kr.", "currency" => "DKK"],
        ["code" => "DJ", "name" => "Djibouti", "phone" => "253", "symbol" => "Fdj", "currency" => "DJF"],
        ["code" => "DM", "name" => "Dominica", "phone" => "1767", "symbol" => "$", "currency" => "XCD"],
        ["code" => "DO", "name" => "Dominican Republic", "phone" => "1809", "symbol" => "$", "currency" => "DOP"],
        ["code" => "EC", "name" => "Ecuador", "phone" => "593", "symbol" => "$", "currency" => "USD"],
        ["code" => "EG", "name" => "Egypt", "phone" => "20", "symbol" => "ج.م", "currency" => "EGP"],
        ["code" => "SV", "name" => "El Salvador", "phone" => "503", "symbol" => "$", "currency" => "USD"],
        ["code" => "GQ", "name" => "Equatorial Guinea", "phone" => "240", "symbol" => "FCFA", "currency" => "XAF"],
        ["code" => "ER", "name" => "Eritrea", "phone" => "291", "symbol" => "Nfk", "currency" => "ERN"],
        ["code" => "EE", "name" => "Estonia", "phone" => "372", "symbol" => "€", "currency" => "EUR"],
        ["code" => "ET", "name" => "Ethiopia", "phone" => "251", "symbol" => "Nkf", "currency" => "ETB"],
        ["code" => "FK", "name" => "Falkland Islands (Malvinas)", "phone" => "500", "symbol" => "£", "currency" => "FKP"],
        ["code" => "FO", "name" => "Faroe Islands", "phone" => "298", "symbol" => "Kr.", "currency" => "DKK"],
        ["code" => "FJ", "name" => "Fiji", "phone" => "679", "symbol" => "FJ$", "currency" => "FJD"],
        ["code" => "FI", "name" => "Finland", "phone" => "358", "symbol" => "€", "currency" => "EUR"],
        ["code" => "FR", "name" => "France", "phone" => "33", "symbol" => "€", "currency" => "EUR"],
        ["code" => "GF", "name" => "French Guiana", "phone" => "594", "symbol" => "€", "currency" => "EUR"],
        ["code" => "PF", "name" => "French Polynesia", "phone" => "689", "symbol" => "₣", "currency" => "XPF"],
        ["code" => "TF", "name" => "French Southern Territories", "phone" => "262", "symbol" => "€", "currency" => "EUR"],
        ["code" => "GA", "name" => "Gabon", "phone" => "241", "symbol" => "FCFA", "currency" => "XAF"],
        ["code" => "GM", "name" => "Gambia", "phone" => "220", "symbol" => "D", "currency" => "GMD"],
        ["code" => "GE", "name" => "Georgia", "phone" => "995", "symbol" => "ლ", "currency" => "GEL"],
        ["code" => "DE", "name" => "Germany", "phone" => "49", "symbol" => "€", "currency" => "EUR"],
        ["code" => "GH", "name" => "Ghana", "phone" => "233", "symbol" => "GH₵", "currency" => "GHS"],
        ["code" => "GI", "name" => "Gibraltar", "phone" => "350", "symbol" => "£", "currency" => "GIP"],
        ["code" => "GR", "name" => "Greece", "phone" => "30", "symbol" => "€", "currency" => "EUR"],
        ["code" => "GL", "name" => "Greenland", "phone" => "299", "symbol" => "Kr.", "currency" => "DKK"],
        ["code" => "GD", "name" => "Grenada", "phone" => "1473", "symbol" => "$", "currency" => "XCD"],
        ["code" => "GP", "name" => "Guadeloupe", "phone" => "590", "symbol" => "€", "currency" => "EUR"],
        ["code" => "GU", "name" => "Guam", "phone" => "1671", "symbol" => "$", "currency" => "USD"],
        ["code" => "GT", "name" => "Guatemala", "phone" => "502", "symbol" => "Q", "currency" => "GTQ"],
        ["code" => "GG", "name" => "Guernsey", "phone" => "44", "symbol" => "£", "currency" => "GBP"],
        ["code" => "GN", "name" => "Guinea", "phone" => "224", "symbol" => "FG", "currency" => "GNF"],
        ["code" => "GW", "name" => "Guinea-Bissau", "phone" => "245", "symbol" => "CFA", "currency" => "XOF"],
        ["code" => "GY", "name" => "Guyana", "phone" => "592", "symbol" => "$", "currency" => "GYD"],
        ["code" => "HT", "name" => "Haiti", "phone" => "509", "symbol" => "G", "currency" => "HTG"],
        ["code" => "HM", "name" => "Heard Island and Mcdonald Islands", "phone" => "0", "symbol" => "$", "currency" => "AUD"],
        ["code" => "VA", "name" => "Holy See (Vatican City State)", "phone" => "39", "symbol" => "€", "currency" => "EUR"],
        ["code" => "HN", "name" => "Honduras", "phone" => "504", "symbol" => "L", "currency" => "HNL"],
        ["code" => "HK", "name" => "Hong Kong", "phone" => "852", "symbol" => "$", "currency" => "HKD"],
        ["code" => "HU", "name" => "Hungary", "phone" => "36", "symbol" => "Ft", "currency" => "HUF"],
        ["code" => "IS", "name" => "Iceland", "phone" => "354", "symbol" => "kr", "currency" => "ISK"],
        ["code" => "IN", "name" => "India", "phone" => "91", "symbol" => "₹", "currency" => "INR"],
        ["code" => "ID", "name" => "Indonesia", "phone" => "62", "symbol" => "Rp", "currency" => "IDR"],
        ["code" => "IR", "name" => "Iran, Islamic Republic of", "phone" => "98", "symbol" => "﷼", "currency" => "IRR"],
        ["code" => "IQ", "name" => "Iraq", "phone" => "964", "symbol" => "د.ع", "currency" => "IQD"],
        ["code" => "IE", "name" => "Ireland", "phone" => "353", "symbol" => "€", "currency" => "EUR"],
        ["code" => "IM", "name" => "Isle of Man", "phone" => "44", "symbol" => "£", "currency" => "GBP"],
        ["code" => "IL", "name" => "Israel", "phone" => "972", "symbol" => "₪", "currency" => "ILS"],
        ["code" => "IT", "name" => "Italy", "phone" => "39", "symbol" => "€", "currency" => "EUR"],
        ["code" => "JM", "name" => "Jamaica", "phone" => "1876", "symbol" => "J$", "currency" => "JMD"],
        ["code" => "JP", "name" => "Japan", "phone" => "81", "symbol" => "¥", "currency" => "JPY"],
        ["code" => "JE", "name" => "Jersey", "phone" => "44", "symbol" => "£", "currency" => "GBP"],
        ["code" => "JO", "name" => "Jordan", "phone" => "962", "symbol" => "ا.د", "currency" => "JOD"],
        ["code" => "KZ", "name" => "Kazakhstan", "phone" => "7", "symbol" => "лв", "currency" => "KZT"],
        ["code" => "KE", "name" => "Kenya", "phone" => "254", "symbol" => "KSh", "currency" => "KES"],
        ["code" => "KI", "name" => "Kiribati", "phone" => "686", "symbol" => "$", "currency" => "AUD"],
        ["code" => "KP", "name" => "Korea, Democratic People's Republic of", "phone" => "850", "symbol" => "₩", "currency" => "KPW"],
        ["code" => "KR", "name" => "Korea, Republic of", "phone" => "82", "symbol" => "₩", "currency" => "KRW"],
        ["code" => "XK", "name" => "Kosovo", "phone" => "381", "symbol" => "€", "currency" => "EUR"],
        ["code" => "KW", "name" => "Kuwait", "phone" => "965", "symbol" => "ك.د", "currency" => "KWD"],
        ["code" => "KG", "name" => "Kyrgyzstan", "phone" => "996", "symbol" => "лв", "currency" => "KGS"],
        ["code" => "LA", "name" => "Lao People's Democratic Republic", "phone" => "856", "symbol" => "₭", "currency" => "LAK"],
        ["code" => "LV", "name" => "Latvia", "phone" => "371", "symbol" => "€", "currency" => "EUR"],
        ["code" => "LB", "name" => "Lebanon", "phone" => "961", "symbol" => "£", "currency" => "LBP"],
        ["code" => "LS", "name" => "Lesotho", "phone" => "266", "symbol" => "L", "currency" => "LSL"],
        ["code" => "LR", "name" => "Liberia", "phone" => "231", "symbol" => "$", "currency" => "LRD"],
        ["code" => "LY", "name" => "Libyan Arab Jamahiriya", "phone" => "218", "symbol" => "د.ل", "currency" => "LYD"],
        ["code" => "LI", "name" => "Liechtenstein", "phone" => "423", "symbol" => "CHf", "currency" => "CHF"],
        ["code" => "LT", "name" => "Lithuania", "phone" => "370", "symbol" => "€", "currency" => "EUR"],
        ["code" => "LU", "name" => "Luxembourg", "phone" => "352", "symbol" => "€", "currency" => "EUR"],
        ["code" => "MO", "name" => "Macao", "phone" => "853", "symbol" => "$", "currency" => "MOP"],
        ["code" => "MK", "name" => "Macedonia, the Former Yugoslav Republic of", "phone" => "389", "symbol" => "ден", "currency" => "MKD"],
        ["code" => "MG", "name" => "Madagascar", "phone" => "261", "symbol" => "Ar", "currency" => "MGA"],
        ["code" => "MW", "name" => "Malawi", "phone" => "265", "symbol" => "MK", "currency" => "MWK"],
        ["code" => "MY", "name" => "Malaysia", "phone" => "60", "symbol" => "RM", "currency" => "MYR"],
        ["code" => "MV", "name" => "Maldives", "phone" => "960", "symbol" => "Rf", "currency" => "MVR"],
        ["code" => "ML", "name" => "Mali", "phone" => "223", "symbol" => "CFA", "currency" => "XOF"],
        ["code" => "MT", "name" => "Malta", "phone" => "356", "symbol" => "€", "currency" => "EUR"],
        ["code" => "MH", "name" => "Marshall Islands", "phone" => "692", "symbol" => "$", "currency" => "USD"],
        ["code" => "MQ", "name" => "Martinique", "phone" => "596", "symbol" => "€", "currency" => "EUR"],
        ["code" => "MR", "name" => "Mauritania", "phone" => "222", "symbol" => "MRU", "currency" => "MRO"],
        ["code" => "MU", "name" => "Mauritius", "phone" => "230", "symbol" => "₨", "currency" => "MUR"],
        ["code" => "YT", "name" => "Mayotte", "phone" => "269", "symbol" => "€", "currency" => "EUR"],
        ["code" => "MX", "name" => "Mexico", "phone" => "52", "symbol" => "$", "currency" => "MXN"],
        ["code" => "FM", "name" => "Micronesia, Federated States of", "phone" => "691", "symbol" => "$", "currency" => "USD"],
        ["code" => "MD", "name" => "Moldova, Republic of", "phone" => "373", "symbol" => "L", "currency" => "MDL"],
        ["code" => "MC", "name" => "Monaco", "phone" => "377", "symbol" => "€", "currency" => "EUR"],
        ["code" => "MN", "name" => "Mongolia", "phone" => "976", "symbol" => "₮", "currency" => "MNT"],
        ["code" => "ME", "name" => "Montenegro", "phone" => "382", "symbol" => "€", "currency" => "EUR"],
        ["code" => "MS", "name" => "Montserrat", "phone" => "1664", "symbol" => "$", "currency" => "XCD"],
        ["code" => "MA", "name" => "Morocco", "phone" => "212", "symbol" => "DH", "currency" => "MAD"],
        ["code" => "MZ", "name" => "Mozambique", "phone" => "258", "symbol" => "MT", "currency" => "MZN"],
        ["code" => "MM", "name" => "Myanmar", "phone" => "95", "symbol" => "K", "currency" => "MMK"],
        ["code" => "NA", "name" => "Namibia", "phone" => "264", "symbol" => "$", "currency" => "NAD"],
        ["code" => "NR", "name" => "Nauru", "phone" => "674", "symbol" => "$", "currency" => "AUD"],
        ["code" => "NP", "name" => "Nepal", "phone" => "977", "symbol" => "₨", "currency" => "NPR"],
        ["code" => "NL", "name" => "Netherlands", "phone" => "31", "symbol" => "€", "currency" => "EUR"],
        ["code" => "AN", "name" => "Netherlands Antilles", "phone" => "599", "symbol" => "NAf", "currency" => "ANG"],
        ["code" => "NC", "name" => "New Caledonia", "phone" => "687", "symbol" => "₣", "currency" => "XPF"],
        ["code" => "NZ", "name" => "New Zealand", "phone" => "64", "symbol" => "$", "currency" => "NZD"],
        ["code" => "NI", "name" => "Nicaragua", "phone" => "505", "symbol" => "C$", "currency" => "NIO"],
        ["code" => "NE", "name" => "Niger", "phone" => "227", "symbol" => "CFA", "currency" => "XOF"],
        ["code" => "NG", "name" => "Nigeria", "phone" => "234", "symbol" => "₦", "currency" => "NGN"],
        ["code" => "NU", "name" => "Niue", "phone" => "683", "symbol" => "$", "currency" => "NZD"],
        ["code" => "NF", "name" => "Norfolk Island", "phone" => "672", "symbol" => "$", "currency" => "AUD"],
        ["code" => "MP", "name" => "Northern Mariana Islands", "phone" => "1670", "symbol" => "$", "currency" => "USD"],
        ["code" => "NO", "name" => "Norway", "phone" => "47", "symbol" => "kr", "currency" => "NOK"],
        ["code" => "OM", "name" => "Oman", "phone" => "968", "symbol" => ".ع.ر", "currency" => "OMR"],
        ["code" => "PK", "name" => "Pakistan", "phone" => "92", "symbol" => "₨", "currency" => "PKR"],
        ["code" => "PW", "name" => "Palau", "phone" => "680", "symbol" => "$", "currency" => "USD"],
        ["code" => "PS", "name" => "Palestinian Territory, Occupied", "phone" => "970", "symbol" => "₪", "currency" => "ILS"],
        ["code" => "PA", "name" => "Panama", "phone" => "507", "symbol" => "B/.", "currency" => "PAB"],
        ["code" => "PG", "name" => "Papua New Guinea", "phone" => "675", "symbol" => "K", "currency" => "PGK"],
        ["code" => "PY", "name" => "Paraguay", "phone" => "595", "symbol" => "₲", "currency" => "PYG"],
        ["code" => "PE", "name" => "Peru", "phone" => "51", "symbol" => "S/.", "currency" => "PEN"],
        ["code" => "PH", "name" => "Philippines", "phone" => "63", "symbol" => "₱", "currency" => "PHP"],
        ["code" => "PN", "name" => "Pitcairn", "phone" => "64", "symbol" => "$", "currency" => "NZD"],
        ["code" => "PL", "name" => "Poland", "phone" => "48", "symbol" => "zł", "currency" => "PLN"],
        ["code" => "PT", "name" => "Portugal", "phone" => "351", "symbol" => "€", "currency" => "EUR"],
        ["code" => "PR", "name" => "Puerto Rico", "phone" => "1787", "symbol" => "$", "currency" => "USD"],
        ["code" => "QA", "name" => "Qatar", "phone" => "974", "symbol" => "ق.ر", "currency" => "QAR"],
        ["code" => "RE", "name" => "Reunion", "phone" => "262", "symbol" => "€", "currency" => "EUR"],
        ["code" => "RO", "name" => "Romania", "phone" => "40", "symbol" => "lei", "currency" => "RON"],
        ["code" => "RU", "name" => "Russian Federation", "phone" => "70", "symbol" => "₽", "currency" => "RUB"],
        ["code" => "RW", "name" => "Rwanda", "phone" => "250", "symbol" => "FRw", "currency" => "RWF"],
        ["code" => "BL", "name" => "Saint Barthelemy", "phone" => "590", "symbol" => "€", "currency" => "EUR"],
        ["code" => "SH", "name" => "Saint Helena", "phone" => "290", "symbol" => "£", "currency" => "SHP"],
        ["code" => "KN", "name" => "Saint Kitts and Nevis", "phone" => "1869", "symbol" => "$", "currency" => "XCD"],
        ["code" => "LC", "name" => "Saint Lucia", "phone" => "1758", "symbol" => "$", "currency" => "XCD"],
        ["code" => "MF", "name" => "Saint Martin", "phone" => "590", "symbol" => "€", "currency" => "EUR"],
        ["code" => "PM", "name" => "Saint Pierre and Miquelon", "phone" => "508", "symbol" => "€", "currency" => "EUR"],
        ["code" => "VC", "name" => "Saint Vincent and the Grenadines", "phone" => "1784", "symbol" => "$", "currency" => "XCD"],
        ["code" => "WS", "name" => "Samoa", "phone" => "684", "symbol" => "SAT", "currency" => "WST"],
        ["code" => "SM", "name" => "San Marino", "phone" => "378", "symbol" => "€", "currency" => "EUR"],
        ["code" => "ST", "name" => "Sao Tome and Principe", "phone" => "239", "symbol" => "Db", "currency" => "STD"],
        ["code" => "SA", "name" => "Saudi Arabia", "phone" => "966", "symbol" => "﷼", "currency" => "SAR"],
        ["code" => "SN", "name" => "Senegal", "phone" => "221", "symbol" => "CFA", "currency" => "XOF"],
        ["code" => "RS", "name" => "Serbia", "phone" => "381", "symbol" => "din", "currency" => "RSD"],
        ["code" => "CS", "name" => "Serbia and Montenegro", "phone" => "381", "symbol" => "din", "currency" => "RSD"],
        ["code" => "SC", "name" => "Seychelles", "phone" => "248", "symbol" => "SRe", "currency" => "SCR"],
        ["code" => "SL", "name" => "Sierra Leone", "phone" => "232", "symbol" => "Le", "currency" => "SLL"],
        ["code" => "SG", "name" => "Singapore", "phone" => "65", "symbol" => "$", "currency" => "SGD"],
        ["code" => "SX", "name" => "Sint Maarten", "phone" => "1", "symbol" => "ƒ", "currency" => "ANG"],
        ["code" => "SK", "name" => "Slovakia", "phone" => "421", "symbol" => "€", "currency" => "EUR"],
        ["code" => "SI", "name" => "Slovenia", "phone" => "386", "symbol" => "€", "currency" => "EUR"],
        ["code" => "SB", "name" => "Solomon Islands", "phone" => "677", "symbol" => "Si$", "currency" => "SBD"],
        ["code" => "SO", "name" => "Somalia", "phone" => "252", "symbol" => "Sh.so.", "currency" => "SOS"],
        ["code" => "ZA", "name" => "South Africa", "phone" => "27", "symbol" => "R", "currency" => "ZAR"],
        ["code" => "GS", "name" => "South Georgia and the South Sandwich Islands", "phone" => "500", "symbol" => "£", "currency" => "GBP"],
        ["code" => "SS", "name" => "South Sudan", "phone" => "211", "symbol" => "£", "currency" => "SSP"],
        ["code" => "ES", "name" => "Spain", "phone" => "34", "symbol" => "€", "currency" => "EUR"],
        ["code" => "LK", "name" => "Sri Lanka", "phone" => "94", "symbol" => "Rs", "currency" => "LKR"],
        ["code" => "SD", "name" => "Sudan", "phone" => "249", "symbol" => ".س.ج", "currency" => "SDG"],
        ["code" => "SR", "name" => "Suriname", "phone" => "597", "symbol" => "$", "currency" => "SRD"],
        ["code" => "SJ", "name" => "Svalbard and Jan Mayen", "phone" => "47", "symbol" => "kr", "currency" => "NOK"],
        ["code" => "SZ", "name" => "Swaziland", "phone" => "268", "symbol" => "E", "currency" => "SZL"],
        ["code" => "SE", "name" => "Sweden", "phone" => "46", "symbol" => "kr", "currency" => "SEK"],
        ["code" => "CH", "name" => "Switzerland", "phone" => "41", "symbol" => "CHf", "currency" => "CHF"],
        ["code" => "SY", "name" => "Syrian Arab Republic", "phone" => "963", "symbol" => "LS", "currency" => "SYP"],
        ["code" => "TW", "name" => "Taiwan, Province of China", "phone" => "886", "symbol" => "$", "currency" => "TWD"],
        ["code" => "TJ", "name" => "Tajikistan", "phone" => "992", "symbol" => "SM", "currency" => "TJS"],
        ["code" => "TZ", "name" => "Tanzania, United Republic of", "phone" => "255", "symbol" => "TSh", "currency" => "TZS"],
        ["code" => "TH", "name" => "Thailand", "phone" => "66", "symbol" => "฿", "currency" => "THB"],
        ["code" => "TL", "name" => "Timor-Leste", "phone" => "670", "symbol" => "$", "currency" => "USD"],
        ["code" => "TG", "name" => "Togo", "phone" => "228", "symbol" => "CFA", "currency" => "XOF"],
        ["code" => "TK", "name" => "Tokelau", "phone" => "690", "symbol" => "$", "currency" => "NZD"],
        ["code" => "TO", "name" => "Tonga", "phone" => "676", "symbol" => "$", "currency" => "TOP"],
        ["code" => "TT", "name" => "Trinidad and Tobago", "phone" => "1868", "symbol" => "$", "currency" => "TTD"],
        ["code" => "TN", "name" => "Tunisia", "phone" => "216", "symbol" => "ت.د", "currency" => "TND"],
        ["code" => "TR", "name" => "Turkey", "phone" => "90", "symbol" => "₺", "currency" => "TRY"],
        ["code" => "TM", "name" => "Turkmenistan", "phone" => "7370", "symbol" => "T", "currency" => "TMT"],
        ["code" => "TC", "name" => "Turks and Caicos Islands", "phone" => "1649", "symbol" => "$", "currency" => "USD"],
        ["code" => "TV", "name" => "Tuvalu", "phone" => "688", "symbol" => "$", "currency" => "AUD"],
        ["code" => "UG", "name" => "Uganda", "phone" => "256", "symbol" => "USh", "currency" => "UGX"],
        ["code" => "UA", "name" => "Ukraine", "phone" => "380", "symbol" => "₴", "currency" => "UAH"],
        ["code" => "AE", "name" => "United Arab Emirates", "phone" => "971", "symbol" => "إ.د", "currency" => "AED"],
        ["code" => "GB", "name" => "United Kingdom", "phone" => "44", "symbol" => "£", "currency" => "GBP"],
        ["code" => "US", "name" => "United States", "phone" => "1", "symbol" => "$", "currency" => "USD"],
        ["code" => "UM", "name" => "United States Minor Outlying Islands", "phone" => "1", "symbol" => "$", "currency" => "USD"],
        ["code" => "UY", "name" => "Uruguay", "phone" => "598", "symbol" => "$", "currency" => "UYU"],
        ["code" => "UZ", "name" => "Uzbekistan", "phone" => "998", "symbol" => "лв", "currency" => "UZS"],
        ["code" => "VU", "name" => "Vanuatu", "phone" => "678", "symbol" => "VT", "currency" => "VUV"],
        ["code" => "VE", "name" => "Venezuela", "phone" => "58", "symbol" => "Bs", "currency" => "VEF"],
        ["code" => "VN", "name" => "Viet Nam", "phone" => "84", "symbol" => "₫", "currency" => "VND"],
        ["code" => "VG", "name" => "Virgin Islands, British", "phone" => "1284", "symbol" => "$", "currency" => "USD"],
        ["code" => "VI", "name" => "Virgin Islands, U.s.", "phone" => "1340", "symbol" => "$", "currency" => "USD"],
        ["code" => "WF", "name" => "Wallis and Futuna", "phone" => "681", "symbol" => "₣", "currency" => "XPF"],
        ["code" => "EH", "name" => "Western Sahara", "phone" => "212", "symbol" => "MAD", "currency" => "MAD"],
        ["code" => "YE", "name" => "Yemen", "phone" => "967", "symbol" => "﷼", "currency" => "YER"],
        ["code" => "ZM", "name" => "Zambia", "phone" => "260", "symbol" => "ZK", "currency" => "ZMW"],
        ["code" => "ZW", "name" => "Zimbabwe", "phone" => "263", "symbol" => "$", "currency" => "ZWL"]
    ],


];

